resources:
- jenkins-cluster.yaml
- namespace.yaml
- secrets.yaml
- oauth-proxy.yaml
- cronjob.yaml
commonAnnotations:
  email: tommylikehu@gmail.com
  owner: tommylikehu
namespace: jenkins-master
images:
- name: swr.cn-north-4.myhuaweicloud.com/openeuler/bak-jenkins
  newTag: fc7cbd36549e0ff0f6f019916a1972ec09c52044
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
