resources:
- ingress.yaml
- service.yaml
- deployment.yaml
- sa.yaml
namespace: website-revision
commonAnnotations:
  kubernetes.ops.cluster: mindspore-cn4-x86
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: gongzhuangbang
  kubernetes.ops.region: beijing
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/mindspore-website
  newTag: v1.0.20240219052221
